### ISSUE TITLE
Prašymas patobulinti

### ISSUE THREAD

**Issue by EvalVis** [GintareLi/PSP#2]
@GintareLi O galima būtų visus validatorių metodus sujungti į vieną "validate" metodą? Nes dabar viską man tektų kviesti atskirai, kas yra nepatogu. Validate metodas turi tik
`    public boolean CheckIfValid() {
        if (email == null)
            return false;
        else
            return true;
    }`

**Comment by GintareLi** [comment]
labu, jo aišku galima. Tu sujungsi ar man sujungti?

**Comment by EvalVis** [comment]
Labas. Dabar prisiminiau, kad dėl testų kažką keitinėti iš tavo pusės būtų nelabai faina. Tai padarysiu iš savo pusės implementaciją, kuri visas validatorių dalis sujungia į vieną.
